### ISSUE TITLE
Include additional error details given by Facebook

### ISSUE THREAD

**Issue by chandlerprall** [revetkn/restfb#164]
In [throwFacebookResponseStatusException](https://github.com/revetkn/restfb/blob/master/source/library/com/restfb/DefaultFacebookClient.java#L966) two parameters are passed along in the thrown error, `type` and `message`. Facebook also provides a `error_user_msg` which is far more descriptive and really aids debugging. Can this additional information be included in the thrown error?

**Comment by nbartels** [comment]
I'll have a look at this...

Here some additional information, how Facebook's error json looks atm.

```json
{
   "error": {
      "message": "Message describing the error", 
      "type": "OAuthException", 
      "code": 190,
      "error_subcode": 460,
      "error_user_title": "A title",
      "error_user_msg": "A message"
   }
}
```

* ```message``` A description of the error intended for the developer.
* ```code``` An error code, some common values for which are listed below, along with common recovery tactics should you detect them.
* ```error_subcode``` Used to further classify an error, common values are shown below.
* ```error_user_msg``` When you encounter this you should show the message directly to the user. It will be correctly translated per the locale of the API request.
* ```error_user_title``` If you are showing an error dialog, this should be the title of the dialog. Again it will be correctly translated per the locale of the API request.

**Comment by chandlerprall** [comment]
Thanks!
