### ISSUE TITLE
restfb fails to parse JSON response when school year is part of response

### ISSUE THREAD

**Issue by suryaganeshv** [revetkn/restfb#168]
Earlier FB was returning school year as String and restfb used to successfully parse the response. Recently FB has changed the response where school year is being returned as integer. Now the JSON parsing is failing with the below exception -

Unable to map JSON to Java. Offending JSON is '1999'. com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '1999'. at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:311) at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:669) at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:292) at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:178) at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:650) at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:292) at com.restfb.Connection.<init>(Connection.java:151)

**Comment by revetkn** [comment]
Thanks!   Can you provide the JSON FB is returning so we can make sure our fix's unit test will be correct?

**Comment by suryaganeshv** [comment]
Please find the sample JSON respone below -

{
    "data": [
        {
            "id": "500110944",
            "education": [
                {
                    "school": {
                        "id": "129254073777235",
                        "name": "Marimallappa's High School"
                    },
                    "type": "High School"
                },
                {
                    "school": {
                        "id": "111951435498089",
                        "name": "PESCE, Mandya"
                    },
                    "type": "College"
                },
                {
                    "school": {
                        "id": "106518946050919",
                        "name": "Marimallappa's PU College"
                    },
                    "year": 1997,
                    "type": "College"
                },
                {
                    "school": {
                        "id": "109846209037854",
                        "name": "BITS Pilani"
                    },
                    "degree": {
                        "id": "184572758248419",
                        "name": "Masters"
                    },
                    "year": 2005,
                    "concentration": [
                        {
                            "id": "104019836301629",
                            "name": "Information Science"
                        }
                    ],
                    "type": "Graduate School"
                },
                {
                    "school": {
                        "id": "106376679414134",
                        "name": "PES College"
                    },
                    "degree": {
                        "id": "109136949164575",
                        "name": "Bachelors"
                    },
                    "year": 2001,
                    "concentration": [
                        {
                            "id": "104076956295773",
                            "name": "Computer Science"
                        }
                    ],
                    "type": "Graduate School"
                }
            ]
        }
    ],
    "paging": {
        "next": "https://graph.facebook.com/v1.0/692967535/friends?fields=id,name,first_name,last_name,middle_name,email,education&limit=1&format=json&access_token=XXXXXX"
    }
}

**Comment by nbartels** [comment]
Thanks for the json. Unittests and a fix added. 

You can get the year with the ```Education#getYearAsString()``` method. The year is returned as ```String``` because we get the year normally in a ```NamedFacebookType``` as String.
