### ISSUE TITLE
Move documentation to GH pages

### ISSUE THREAD

**Issue by marcelstoer** [revetkn/restfb#171]
At the moment nearly the same content has to be maintained twice for http://restfb.com and in README.md.
I suggest you fully embrace GitHub by moving the documentation to [GitHub Pages](https://help.github.com/categories/github-pages-basics/). This would allow to remove the `website` folder from the the master branch (extra benefit). restfb.com could be changed to (semi-)automatically forward to the GitHub documentation.

**Comment by nbartels** [comment]
I think the homepage and the readme are not the same. The readme is only a subset of the homepage. But I like the idea to make the deployment more automatically. We will talk about this internally. 

Thanks for the input.

**Comment by marcelstoer** [comment]
> I think the homepage and the readme are not the same.

Yes, indeed. I just noticed that currently it's more or less the same content. Even if restfb.com forwards to the GitHub Pages site you could still keep a very brief intro on the readme and link to the GitHub Pages site from there, too.
