### ISSUE TITLE
Graph API v2.2 - (#803) Cannot query users by their username (btaylor) (code 803, subcode null)

### ISSUE THREAD

**Issue by fuzzybee** [revetkn/restfb#175]
May I check with you which version of the Facebook Graph API restfb is supposed to work with? Or is it the latest - v2.2?

I'm getting
`Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#803) Cannot query users by their username (btaylor) (code 803, subcode null)`
When following your example:
`JsonObject btaylor = facebookClient.fetchObject("btaylor", JsonObject.class);`

Thank you

**Comment by nbartels** [comment]
With Graph API Version 2.2 the possibility to fetch a user by name is removed. Older Api Version should still work.

We have to rework the example and documentation. THX for your input

**Comment by fuzzybee** [comment]
Thank you Norbert
