### ISSUE TITLE
constructor DefaultFacebookClient in class DefaultFacebookClient is deprecated

### ISSUE THREAD

**Issue by btd** [revetkn/restfb#176]
Since 1.7.1 default constructor for DefaultFacebookClient was deprecated, and it is mentioned that for replace it need to use 
```
As of release 1.7.1, replaced by DefaultFacebookClient(java.lang.String, com.restfb.Version)
```
Which is not right. Because default constructor helps when you need to obtain app access token like:
```
new DefaultFacebookClient()
      .obtainAppAccessToken(Properties.facebookApiId, Properties.facebookApiSecret)
      .getAccessToken
```
So that really should be constructor:
```
DefaultFacebookClient(com.restfb.Version)
```
Am i right, or for 1.7.1 appeared something new to get app access token?

**Comment by nbartels** [comment]
You're right the constructor is missing. I add it asap.

**Comment by btd** [comment]
Thanks. When it will be published?

**Comment by nbartels** [comment]
Good question, I cannot give you a concrete date, because I think it would be nice to fix some other stuff. The #177 (User age range) and the #171 (GH pages) should be fixed/solved first, but afterwards a release should be possible.
