### ISSUE TITLE
facebook insights are not gettting 

### ISSUE THREAD

**Issue by madhukotagiri** [revetkn/restfb#178]
Hi ,
I am using the rest fb face book insights 
i am created an app in Facebook and taken the appid and secret code in the code and 
i want to read the insight feeds of page.
i have my own page..
i am able read the insights with my credentials.
i made another one as admin to that page. but with his credentials i am not able to read the insights.
i given all  permissions in graph api.
i cross checked with another page and another credentials also.
totally i crosschecked the all the scenarios.
still i am facing the issue.

here is my code its working fine for my own page and and my credentials.

public static ArrayList<InsightViewsPojo> getInsights(FacebookClient facebookClient,String postID){
		
		ArrayList<InsightViewsPojo> insightViewsArrayList=new ArrayList<InsightViewsPojo>();
		Connection<Insight> insights = facebookClient.fetchConnection(postID+"/insights", Insight.class);
		Iterator<?> iterator=insights.getData().iterator();
	
		while (iterator.hasNext()) {
			Insight insightsview=(Insight) iterator.next();
			List<JsonObject> jsonObjects=insightsview.getValues();
			InsightViewsPojo insightViewsPojo=null;
			for (int i = 0; i < jsonObjects.size(); i++) {
				insightViewsPojo=new InsightViewsPojo();
				if (insightsview.getName().equalsIgnoreCase("post_impressions_unique")) {
					System.err.println("==TOTAL PEOPLE REACHED=="+jsonObjects.get(i).get("value"));
					insightViewsPojo.setPeopleReached(jsonObjects.get(i).get("value").toString());
				}if (insightsview.getName().equalsIgnoreCase("post_engaged_users")) {
					insightViewsPojo.setPeopleReached(jsonObjects.get(i).get("value").toString());
					System.err.println("==TOTAL PEOPLE ENGAGED=="+jsonObjects.get(i).get("value"));
				}
				insightViewsArrayList.add(insightViewsPojo);
			}
		}
		return insightViewsArrayList;
			
		
	}

but another credentials for this is  i am not able to getting the feeds(i made him admin).

here is my page id : 145769072179423 
please help me in this

**Comment by nbartels** [comment]
do you get an error message / exception or is the ```insights.getData()``` just empty

**Comment by madhukotagiri** [comment]
just empty iam getting the response
but from fb graph tool iam seeing the response

**Comment by nbartels** [comment]
Hm, If I get you right, everything's fine with your account and the source code above. But with the other account the source code is not working. The Graph API Explorer is working in both cases.

Can you please double check that you use the right access token in the app and in the graph api explorer?

I cannot imagine why the source code should not work with another account. Perhaps there's something wrong with the tokens or you found an facebook bug :smile:

**Comment by madhukotagiri** [comment]
please clarify one thing...
example: iam the owner of page XXXXX
i used my credentials to get the insights...it is working fine...:) 
if i use another person credentials to get the insights of my page XXXXX
is it works ?

**Comment by nbartels** [comment]
It should work if that person is an admin or is allowed to view the page insights on facebook. The analyst role for example.

**Comment by nbartels** [comment]
Your problem still exists? Otherwise I'd like to close the issue ...

**Comment by madhukotagiri** [comment]
you please post the snippet here for get the ratings and rating text  the page of face book 
i am closing the issue
