### ISSUE TITLE
getCommentsCount() returns zero

### ISSUE THREAD

**Issue by sercankd** [revetkn/restfb#185]
This function returns always 0 (zero) value.

**Comment by nbartels** [comment]
That's true, if the field ```comments.summary(true)``` is *not* provided. Facebook adds the comment count information only if requested. So you have to change the call to your post. 

For example similar to this:
```java
Post gotPost =
        client.fetchObject("<postid>", Post.class,
          Parameter.with("fields", "from,to,likes.summary(true),comments.summary(true)"));
```

**Comment by sercankd** [comment]
yes that solved the problem. thanks
