### ISSUE TITLE
how to get verification code from facebook ?

### ISSUE THREAD

**Issue by JaneDsouza** [revetkn/restfb#93]
how to get verification code from facebook ?

**Comment by johnou** [comment]
Extend DefaultFacebookClient and create your own method?

        public AccessToken obtainAccessToken(String appId, String appSecret, String redirectUri, String verificationCode) {
            verifyParameterPresence("appId", appId);
            verifyParameterPresence("appSecret", appSecret);
            verifyParameterPresence("verificationCode", verificationCode);
            verifyParameterPresence("redirectUri", redirectUri);

            String response = makeRequest("oauth/access_token", Parameter.with("client_id", appId),
                    Parameter.with("client_secret", appSecret), Parameter.with("code", verificationCode),
                    Parameter.with("redirect_uri", redirectUri));

            try {
                return AccessToken.fromQueryString(response);
            } catch (Throwable t) {
                throw new FacebookResponseContentException("Unable to extract access token from response.", t);
            }
        }

**Comment by nbartels** [comment]
Thx to @johnou. No we can finally close this issue :smile:
